### ISSUE TITLE
Formalize and extend language transclusion

### ISSUE THREAD

**Issue by bollwyvl** [krassowski/jupyterlab-lsp#191]
## Elevator Pitch

Allow a user to define rules for finding parts of files in a host language that embed other languages. Additionally support referring to the outer language within the inner language. Language servers, libraries, and other things a user might have installed should be easily and robustly able to ship and activate these on installation.

## Motivation

Much like with #190 for #189, there are more languages that embed other languages than we'll be able to (or want to) define/maintain. The [existing list](https://github.com/krassowski/jupyterlab-lsp/blob/f8eaa9a6193710c3a161b74e45ac3dbb14d45270/packages/jupyterlab-lsp/src/extractors/defaults.ts#L26) includes things from IPython built-ins, but doesn't fully capture the scope of other magics, much less what other languages do, especially _extremely_ crazy things like [allthekernels](https://github.com/minrk/allthekernels), [sos](https://github.com/vatlab/sos-notebook) or [metakernel](https://github.com/Calysto/metakernel).

A number of these kinds of things also allow for referring to the outer language, such as `{variable}` references, up to full-blown templating languages, and having access to completion/diagostics/reference/hover for these nested scopes would be very valuable.

## Design Ideas

Add a separate spec to the JSON schema, e.g. `transclusions` which can be defined/modified without re-compiling lab by traitlets config or `entry_points`. Move the existing "simple" ones from the hard-coded typescript into defaults on the python side, or simple JSON.

### Notional "Simple" Example
```yaml
LanguageServerManager:
  language_servers: ...
  transclusions:
    ipython-shell-magics:
      host:
        mime_types: 
          - text/x-python
        languages: 
          - python
        file_extensions:
          - .ipy
          - .ipynb
      guest:
        mime_types:
          - application/x-sh
        languages: 
          - sh
        file_extensions:
          - .sh
      patterns:
        line-magic:
          regex: "(?<=\\s)!(.*)$"
          extract: $1
          isolate: true
          host_inclusions:
            variable:
              pattern: "(?<!\\$)\\{([^\\}]+)\\}"
              extract: $1
        cell-magic:
          regex: "^%%bash[^\n]*\n([\n.]+)$"
          extract: $1
          isolate: true
          host_inclusions:
            variable:
              pattern: "(?<!\\$)\\{([^\\}]+)\\}"
              extract: $1
```

### More complex things
These would be insufficient for complicated tricks like what's happening in the some of the r-in-python with declaring variables, and for this case being able to `register` these from an extension that depends on the to-be `ILanguageServerManager` (or a dedidcated `ITransclusionManager`) would be required. 

### User-serviceable and discoverable
Probably need to be configurable in the frontend, e.g. 
- adding/testing new transclusions
- disabling installed ones
- some kind of visual indication of them (gutter?)

**Comment by krassowski** [comment]
Pros:
   - it's just feels so natural to have this in server spec
Cons:
  - typescript extensions are easier to install and update (and as already mentioned allow for more than regexpr)

**Comment by krassowski** [comment]
> some kind of visual indication of them (gutter?)

+100

**Comment by krassowski** [comment]
Overall I agree that this is the right direction, as it would allow anyone who writes a `LanguageServerManager` to appreciate the potential configuration options; having them try to go with regexpr and only then fall-back to typescript extension is reasonable - we will need the `LanguageServerManager` anyways.

**Comment by bollwyvl** [comment]
> typescript extensions are easier to install and update (and as already
mentioned allow for more than regexpr)

Disagreed. So long as npm, nodejs, and webpack are in the mix, this is
peril-fraught. Putting a json file in a place (even checked into you're
project) is about as low effort as you can get. Also the overlap of kernel
authors and js/ts people is relatively small, while most packagers will
suffer through a little Json munging.

**Comment by bollwyvl** [comment]
While thinking about #201, another interesting one:

```yaml
LanguageServerManager:
  language_servers: ...
  transclusions:
    ipython-shell-magics:
      host:
        mime_types: 
          - text/x-dockerfile
        languages: 
          - dockerfile
        file_extensions:
          - Dockerfile
      guest:
        mime_types:
          - application/x-sh
        languages: 
          - sh
        file_extensions:
          - .sh
      patterns:
        RUN:
          regex: "^\\sRUN\\s+(.*)$"
          extract: $1
          isolate: true
```

The wrinkle here is getting the `ARG` and `ENV` tokens into scope.
