### ISSUE TITLE
JupyterLab 3 support using repo2docker / binder

### ISSUE THREAD

**Issue by aplamada** [krassowski/jupyterlab-lsp#503]
`jupyterlab-lsp` is great and I am trying to use it with the new JupyterLab 3.

I tried to build a binder ready project (see below the configuration files) it looks like I still had to do in the postBuild
```shell
jupyter serverextension enable --py jupyter_lsp  --sys-prefix
```

Is this as expected?

----

- `environment.yml` file:

```yaml
channels:
  - conda-forge

dependencies:
  - python >=3.6,<3.9.0a0
  - jupyterlab >=3.0.0,<4.0.0a0
  - jupyter-offlinenotebook >=0.2
  - jupyterlab-lsp=3.3.0
  - jupyter-lsp-python=1.1.2
```

- `postBuild` file:
```shell
set -e

jupyter serverextension enable --py jupyter_lsp  --sys-prefix
```
