### ISSUE TITLE
Enhance language server spec

### ISSUE THREAD

**Issue by bollwyvl** [krassowski/jupyterlab-lsp#89]
For https://github.com/krassowski/jupyterlab-lsp/pull/81#issuecomment-548042214

The current spec is a little limited as revealed in #81 for really driving UI. A more complete spec might be something like (not suggesting YAML, just easier to write):
```yaml
# from spec version 0
argv: 
  - pyls
languages:
  - python
# definitely want
display_name: pyls
mime_types: # could be the source-of-truth instead of guessing in client
  - text/python
  - text/x-ipython
urls:
  home: https://github.com/palantir/python-language-server
  issues: https://github.com/palantir/python-language-server/issues
debug_argv: # will be complicated with helpers, e.g. r
  - pyls
  - v
# nice-to-have
config_schema: # it would be better to have these on the ts side, but...
  pyls.plugins.pydocstyle.enabled:
    type: boolean
    # so much more...
    # https://github.com/palantir/python-language-server/blob/develop/vscode-client/package.json
install: # for docs only
  pip: pip install python-language-server[all]
  conda: conda install -c conda-forge python-language-server
extend: # at least a few other servers are extensible
  - display_name: mypy 
    install: ...
  - display_name: isort
    install: ...
  - display_name: black
    install: ...
environment: # just because kernels have them
  PYTHONUNBUFFERED: "1"
```

This would necessitate a bump to the `entry_point` spec version, e.g. `jupyter_lsp_spec_v1`, though it may be possible to maintain backwards compatibility...
